name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Stop service
        run: sudo systemctl stop PasteBin.service
      - name: Publish
        run: dotnet publish PasteBin/PasteBin.csproj -c Release -o /home/tzer0m/Services/PasteBin
      - name: Start service
        run: sudo systemctl start PasteBin.service
      - name: Check status
        run: sudo systemctl status PasteBin.service --no-pager
